import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./ReactQueryProvider";
import { Suspense } from "react";

const dmsans = DM_Sans({
  variable: "--font-dm",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmsans.className} antialiased`}
      >
        <ReactQueryProvider>
          <Suspense fallback={
            <div className="w-full h-screen flex items-center justify-center">
              <div className="text-sm text-grey-700">Loading...</div>
            </div>
          }>
            {children}
          </Suspense>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
